apiVersion: apps/v1
kind: Deployment
metadata:
  name: galleryapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galleryapp
  template:
    metadata:
      labels:
        app: galleryapp
    spec:
      containers:
      - name: galleryapp
        image: pavangudiwada/galleryapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: galleryapp-service
spec:
  type: NodePort
  selector:
    app: galleryapp
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30007

